FROM node:18-alpine

WORKDIR /app

# Server dependencies are at ROOT
COPY package*.json ./

RUN npm install --omit=dev --no-audit --no-fund

# Server code lives in /server
COPY server ./server

EXPOSE 3000

CMD ["node", "server/index.js"]
