FROM node:18-alpine

WORKDIR /app

# Copy ONLY server package files
COPY server/package*.json ./

# Install prod dependencies
RUN npm install --omit=dev

# Copy server source code
COPY server ./server

EXPOSE 3000

CMD ["node", "server/index.js"]
