# ---------- Build stage ----------
FROM node:18-alpine AS build
WORKDIR /app

COPY client/package*.json ./
RUN npm install

COPY client .
RUN npm run build

# ---------- Runtime stage ----------
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80